# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20160105_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, help_text=b'You may attach a file or screenshot if it helps to explain this issue better.', upload_to=b'uploads/issues/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2016, 6, 4)),
        ),
    ]
