# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20160505_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2016, 6, 5)),
        ),
    ]
