# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 17:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20160506_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='path_as_list',
            field=models.CommaSeparatedIntegerField(default=0, editable=False, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2016, 6, 9)),
        ),
    ]
