# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-28 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_auto_20180110_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
